### ISSUE TITLE
Doesnt seem to work at all

### ISSUE THREAD

**Issue by fergiemcdowall** [pouchdb/pouchdb-fauxton-chrome-extension#5] opened 2015-05-01 06:16 UTC
Hi!

This extension doesnt seem to work at all on my set up (OSX 10.10.3 + Chrome 42.0.2311.135 (64-bit) + pouch 3.4.0). When I click on the extension tab in developer tools I just see blank panes

Any tricks or hacks to coax it into life?

**Comment by fergiemcdowall** [comment] 2015-05-01 06:19
![screen shot 2015-05-01 at 08 18 14](https://cloud.githubusercontent.com/assets/1122333/7427410/cb2e627a-efda-11e4-89dc-56c51db3cbcb.png)

**Comment by marten-de-vries** [comment] 2015-05-03 18:06
Thanks for reporting!

Hmm, that's what Fauxton looks like if no JS is executed. I don't know what could cause it though. You could try to enable developer mode in chrome://extensions/ and see if that gives extra debug information. (I don't have access to OSX at the moment myself to test.) That might help identifying the issue.

**Comment by fergiemcdowall** [comment] 2015-05-09 06:34
as far as I can see, developer mode is on. Will experiment a bit more...

**Comment by remithomas** [comment] 2015-06-04 03:16
I got the same error on Chrome 43

**Comment by marten-de-vries** [comment] 2015-06-04 15:23
Well, as I said, this is Fauxton when no JS is executed. The only realistic scenario's I can think of where that happens, are:

1) script blockers (like NoScript in Firefox, Chrome no doubt has similar addons)
2) and more likely: a bug in pouchdb-fauxton-chrome-extension's code, resulting in a crash. When that happens, some kind of hint should be visible when the developer mode is on.

I can't reproduce this myself, so if there is any more info you could provide, that would be great.

@remithomas @fergiemcdowall

**Comment by remithomas** [comment] 2015-06-05 00:54
Here the console log

``````
Unchecked runtime.lastError while running tabs.executeScript: Cannot access contents of url "chrome-devtools://devtools/bundled/devtools.html?&remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@195776/&dockSide=undocked&toolbarColor=rgba(230,230,230,1)&textColor=rgba(0,0,0,1)". Extension manifest must request permission to access this host.
    at injectContentScript (chrome-extension://hbhhpaojmpfimakffndmpmpndcmonkfa/background.js:20:15)
    at portHandlers.devtools.js (chrome-extension://hbhhpaojmpfimakffndmpmpndcmonkfa/background.js:8:5)reportIfUnchecked @ extensions::lastError:133handleResponse @ extensions::sendRequest:78```

As I said OsX 10.10.3 - Chrome 43.0.2357.81 (64-bit)
``````

**Comment by fergiemcdowall** [comment] 2015-06-05 07:18
Thanks for the message @marten-de-vries 

No, I dont use a script blocker because that would make absolutely no sense while doing client side JavaScript development, so yes a bug or even an obscure security setting seems to be the likely cause :)

**Comment by remithomas** [comment] 2015-06-08 14:20
I tested on other platform, I got the same issue on 
- Win 7 
- Chrome Version 43.0.2357.81 m
- Without script blocker

``````
Unchecked runtime.lastError while running tabs.executeScript: Cannot access contents of url "chrome-devtools://devtools/bundled/devtools.html?&remoteBase=https://chrome…&dockSide=undocked&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)". Extension manifest must request permission to access this host.
    at injectContentScript (chrome-extension://hbhhpaojmpfimakffndmpmpndcmonkfa/background.js:20:15)
    at portHandlers.devtools.js (chrome-extension://hbhhpaojmpfimakffndmpmpndcmonkfa/background.js:8:5)reportIfUnchecked @ extensions::lastError:133handleResponse @ extensions::sendRequest:78```
``````

**Comment by foucdeg** [comment] 2015-06-18 08:18
Same here.
- Win7
- Chrome 43.0.2357.124 m (used with --disable-web-security switch to allow CORS / XHR requests to files)
- and no other extensions at all.

**Comment by remithomas** [comment] 2015-06-21 22:31
I found a solution! It was the permissions and web accessible resources:
https://github.com/remithomas/pouchdb-fauxton-chrome-extension/tree/patch-1

**Comment by fergiemcdowall** [comment] 2015-06-22 07:47
Great! How do I test?

**Comment by foucdeg** [comment] 2015-06-22 07:48
@remithomas awesome, please let us know when it goes to master (does the extension automatically get updated?)

**Comment by marten-de-vries** [comment] 2015-06-22 08:47
Just opened a PR (#6) using that branch. I'll publish to the google store as soon as it's merged.

**Comment by marten-de-vries** [comment] 2015-06-22 08:53
@fergiemcdowall To test, check out the branch @remithomas linked, follow [the build instructions](https://github.com/marten-de-vries/pouchdb-fauxton-chrome-extension/#building) and finally load the result into chrome using [the instructions on Google's developer website](https://developer.chrome.com/extensions/getstarted#unpacked).

**Comment by fergiemcdowall** [comment] 2015-06-22 08:55
Thanks- will do

**Comment by empyrical** [comment] 2015-07-12 03:24
The error I get when I try to use the PouchDB inspector on the background page of a Chrome extension looks exactly like this too. And the error is a `Cannot access contents of url` error, but for a `chrome-extension://` URL.

**Comment by foucdeg** [comment] 2015-07-15 15:14
@marten-de-vries Can you tell us when is it going to be merged and published?
I would build @remithomas 's version from source but I'm getting an error at `npm install`
because of the absence of a file (package.json).

**Comment by deadlyfingers** [comment] 2015-08-05 20:27
I get the same blank view as above, but I get an error in the console:
"Uncaught TypeError: PouchDB.defaults is not a function"

**Comment by marten-de-vries** [comment] 2015-08-18 13:54
@deadlyfingers That error is probably due to using a very old version of PouchDB (one that doesn't support PouchDB.defaults yet). It would probably be nice if the extension/addon detected that and gave a more helpful error, but if you want to pursue that problem please open a separate bug.

**Comment by marten-de-vries** [comment] 2015-08-18 16:35
@foucdeg Sorry for not responding for a while, I've been on a holiday. Anyway, I'm getting the same error, I'm currently working on https://github.com/pouchdb/express-pouchdb/issues/232 , and in the process solving the error it gives (by removing es3ify everywhere). As soon as that is done, this should be unblocked and will be next.

**Comment by marten-de-vries** [comment] 2015-08-19 11:03
Fixed build errors. I still can't reproduce this myself, but I guess there's no harm in merging that PR and republishing to the chrome store. Will close this issue as soon as that's done. If it isn't fixed (i.e., if the bug is something else), please reopen.

**Closed as completed** 2015-08-19 11:10 UTC

**Comment by empyrical** [comment] 2015-08-19 17:38
I confirmed that my problem (unable to inspect a pouch db in a background page) is unrelated - it seems as there's no way for you to give pouch db inspector permission to inject content scripts into a chrome-extension url as they removed the ability to do that

**Comment by foucdeg** [comment] 2015-08-21 07:26
Not solved for me. I don't know how I can be sure that the extension was
updated though, since apparently the version number didn't change.

2015-08-19 19:38 GMT+02:00 empyrical notifications@github.com:

**Comment by marten-de-vries** [comment] 2015-08-21 09:42
@foucdeg Ah, I did upload the app to the chrome store but is was still unpublished. Published it now. Please try again.

**Comment by foucdeg** [comment] 2015-08-21 09:49
It works!
You seem to have changed the type of extension, so now we have to allow it
to be installed as a background app, and in my case I had to tick the
"allow access to files" (or whatever the exact English wording is) checkbox.
Thanks!

2015-08-21 11:42 GMT+02:00 Marten de Vries notifications@github.com:

**Comment by marten-de-vries** [comment] 2015-08-22 08:11
@foucdeg Yes, the PR I merged demanded a lot of new permissions. I would've liked to check if all were absolutely necessary, but since I can't reproduce this I had no other option than blind merging. Anyway, a few pop ups is probably worth it if it makes it work again.

**Comment by jareth** [comment] 2015-11-19 19:53
@deadlyfingers I also had "Uncaught TypeError: PouchDB.defaults is not a function" that was caused by adding the wrong object to window.PouchDB.

This results in the error above:

``` javascript
PouchDB = require('pouchdb');
pouchdb = new PouchDB('myDB');
window.PouchDB = pouchdb;
```

It should be this:

``` javascript
PouchDB = require('pouchdb');
pouchdb = new PouchDB('myDB');
window.PouchDB = PouchDB;
```

**Comment by arumuganainar** [comment] 2016-12-12 07:18
i got same error on chrome 54 (windows 32-bit)
